name: Add contributors
on:
  push:
    branches:
      - main

jobs:
  add-contributors:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - run: |
          git config --global user.email "Github Contributors"
          git config --global user.name "contributors@avency.de"
          git fetch
          git checkout contributors
          git push --set-upstream origin contributors

      - uses: BobAnkh/add-contributors@master
        with:
          CONTRIBUTOR: '### Contributors'
          COLUMN_PER_ROW: '6'
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IMG_WIDTH: '100'
          FONT_SIZE: '14'
          PATH: '/CONTRIBUTORS.md'
          COMMIT_MESSAGE: 'docs(README): update contributors'
          AVATAR_SHAPE: 'round'
          PULL_REQUEST: 'main'
          BRANCH: 'contributors'
